apiVersion: ENC[AES256_GCM,data:Ojg=,iv:957A3j2Hj2wL02l0BjNTMNrz7NBukcgtm6ghlAevhQk=,tag:qlGX+gjKL4GqD0pn73gVag==,type:str]
kind: ENC[AES256_GCM,data:Dr+jb7OM,iv:m+KMzbplgJcXT0+3t7Dg9qvqsnC8c30vDKZPuTSN1lw=,tag:JVhvIBSZjpUGXByE1z0Iog==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7cGyvQ6MMSlE0S+Nnw==,iv:UIZwoMzrExC8vL1ZW+BjO61fXwoI7pkhng/rRTcO9d4=,tag:Iy0t8P4pDsoa8MEN2uWtYQ==,type:str]
    namespace: ENC[AES256_GCM,data:zzUw1mscIZATZQ==,iv:XEGNqYoygd/q9g9jEeoQyT1Dth18uMPTLwlm8nFdpqE=,tag:xIwr8YLUB52MGeSFOT2I8A==,type:str]
type: ENC[AES256_GCM,data:5g9+rb9X,iv:aVbyx9qrTb0RZdYmFZ8KuxtHAnsAb73EBGWBGQ7fd5I=,tag:RW4c3/nCYTTtb5qNq0ou5Q==,type:str]
stringData:
    password: ENC[AES256_GCM,data:nGLz688=,iv:bDVBTVXysTAtQnGF+2/RhUl1yRtTqJWpqc6SVMHl21U=,tag:Y5WgDo5UudwJ5G4uJ/XuLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rpc4hv7mcpcd8jdwmqxfmfd2jjwggdljnfunl78l22z638s0ppfs7yn8ue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMUpxZDk2TjVwVnh4ZC9a
            UW9QWlRjb3Bnb2V4OS8wc3gzUEJRNk5IdkJvCmtVQXBZdHlsZVVhNnZoMFJLQUps
            N0cwYWVoT3NzNFRCNGZpeExWN0NiVnMKLS0tIDhGQkZpWjN3LytHdXg5Q3h6Wm5u
            dTNWYWxWSDhWaXRZNUNtYXRrbVU5VXMKn9dB/n7GGwrfH+2LXKoBH7kJ0KM+kaI1
            SbYoiu5SxkbrVZ2S79PifgNYYD6Sin+HEZzVICmLiBQJjtYoQg3U0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T17:26:43Z"
    mac: ENC[AES256_GCM,data:9ef3Xyq8RzC30IQ9zq/izfyK4/0TU82HdUsmP490e74+hbK/j3qeHOkVe6mI96MC8mJ0WIw7/RgXVf/xf2+KDRhut9vXFgMpgqGsJHxb9CBHSyJ+OkvCXrfmBttMLulfIHXZz+gK6oCEy88HH8PGLKO9wZ/AL7iZyA+UlY4duSI=,iv:tBZrCcMRr6L29tgNXBwMgJLQwu0vOpNNOXJjtwRFkcY=,tag:SA+yp0F7gTmfij+LD6qnRA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
