---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-exporter
  template:
    metadata:
      labels:
        app: mqtt-exporter
    spec:
      containers:
        - name: mqtt-exporter
          image: kpetrem/mqtt-exporter:latest
          ports:
            - containerPort: 9234
          env:
            - name: MQTT_ADDRESS
              value: "mosquitto"
            - name: MQTT_PORT
              value: "1883"
            - name: MQTT_TOPIC
              value: "iot/#"
            - name: PROMETHEUS_PORT
              value: "9234"
            - name: LOG_LEVEL
              value: "INFO"
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-exporter
  namespace: monitoring
spec:
  selector:
    app: mqtt-exporter
  ports:
    - port: 9234
      targetPort: 9234
