apiVersion: ENC[AES256_GCM,data:VyU=,iv:B9RD4Wd6N3YQwNQlas2weoQufgU1GpliBBNK2F56ghk=,tag:wYBt3Vqt8IbHCnvAMNZ91A==,type:str]
kind: ENC[AES256_GCM,data:a7T0zzzV,iv:dzjF5DAbbeVUmAFaIPp00TklHujOvefqtE7JGoFMHEA=,tag:ptjd1JGowkOsknlJ2QfP1Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KjUHJi/McMkalU/7rag=,iv:+FT/4MdSEZuA7I50+PJqZYn5q4UR22SHFZQr/ocGtPw=,tag:acVtFPXFlBLxpx0crapN/w==,type:str]
    namespace: ENC[AES256_GCM,data:iPGn,iv:6Shn0YsIq1PPE6igAYxcn25zpG59oRvSLpMcF8LItac=,tag:BGgRF5MectWYVEqE1TaS0Q==,type:str]
type: ENC[AES256_GCM,data:foMU+PTt,iv:I//RdaRlNZaxRGBWJnbsfZ0FPCxKnoTVXqEb9FSgDdY=,tag:/zvkixWxjDj8YGkew46QjA==,type:str]
stringData:
    NC_PASS: ENC[AES256_GCM,data:vCnuHgJE9x5wBK/XnmCDK69q6b2BjUnRpwB6a3U=,iv:722SgDV4phZCdPUqOTWz01HK/popoRcQd6Vwl+OprR0=,tag:ZmE9GTeJ1+J4FANEpwbbbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rpc4hv7mcpcd8jdwmqxfmfd2jjwggdljnfunl78l22z638s0ppfs7yn8ue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb0VrN2Q4eVQzUE5TQUJW
            cFlVSC9zUGtzSEUva0t5dklnazhaSEM0SWcwCnlnaW9BUWx0Q2h3L3VvODQ3UDdo
            STRGOWdwUUpaUGlXV2NveDgyTHNTNTAKLS0tIGRBRzdWK2dlbStmOFYyWWtPSlZP
            UWRoeCsxZGl3cTRKM1lXT2plNkFjZDAKoVcTi14hGQ67mLVw98XnNJrr0Z3K6JR6
            SoMGKvzX5bLLsHrSmpXNOy2UnDlLa1PZdOhrPliDNZzE/JSKPBMQfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T17:26:38Z"
    mac: ENC[AES256_GCM,data:kEkngN+5bwgAeu1OmrbUPOr+gAv2VESmGQAUO3j4SK5kSXWTvlUF55basZnC+/+0AuMqjiT2um1H5krBOmy45dXg8Rv0XQEi9On7m5ZRxbJ7+7ka7DvXjcndjBjNpgW/vFpZyEstfj1fjLVSa9AVzQEYxW/bd8sUMCyg1FAjiX0=,iv:mWLcYzFOnUzxH5YZOakjwR/r7alG2mt4uVCSqKMh7BY=,tag:xhkLI8oW+99a+eJdwWjlqw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
